# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T12:49:42+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, List, Optional

from pydantic import BaseModel, Field, RootModel, constr


class ApplyMethod(Enum):
    immediate = 'immediate'
    pending_reboot = 'pending-reboot'


class AuthorizationNotFoundFault(RootModel[Any]):
    root: Any


class Boolean(RootModel[bool]):
    root: bool


class BooleanOptional(RootModel[bool]):
    root: bool


class CertificateNotFoundFault(RootModel[Any]):
    root: Any


class DBClusterAlreadyExistsFault(RootModel[Any]):
    root: Any


class DBClusterEndpointAlreadyExistsFault(RootModel[Any]):
    root: Any


class DBClusterEndpointNotFoundFault(RootModel[Any]):
    root: Any


class DBClusterEndpointQuotaExceededFault(RootModel[Any]):
    root: Any


class DBClusterNotFoundFault(RootModel[Any]):
    root: Any


class DBClusterParameterGroupNotFoundFault(RootModel[Any]):
    root: Any


class DBClusterQuotaExceededFault(RootModel[Any]):
    root: Any


class DBClusterRoleAlreadyExistsFault(RootModel[Any]):
    root: Any


class DBClusterRoleNotFoundFault(RootModel[Any]):
    root: Any


class DBClusterRoleQuotaExceededFault(RootModel[Any]):
    root: Any


class DBClusterSnapshotAlreadyExistsFault(RootModel[Any]):
    root: Any


class DBClusterSnapshotNotFoundFault(RootModel[Any]):
    root: Any


class DBInstanceAlreadyExistsFault(RootModel[Any]):
    root: Any


class DBInstanceNotFoundFault(RootModel[Any]):
    root: Any


class DBParameterGroupAlreadyExistsFault(RootModel[Any]):
    root: Any


class DBParameterGroupNotFoundFault(RootModel[Any]):
    root: Any


class DBParameterGroupQuotaExceededFault(RootModel[Any]):
    root: Any


class DBSecurityGroupNotFoundFault(RootModel[Any]):
    root: Any


class DBSnapshotAlreadyExistsFault(RootModel[Any]):
    root: Any


class DBSnapshotNotFoundFault(RootModel[Any]):
    root: Any


class DBSubnetGroupAlreadyExistsFault(RootModel[Any]):
    root: Any


class DBSubnetGroupDoesNotCoverEnoughAZs(RootModel[Any]):
    root: Any


class DBSubnetGroupNotFoundFault(RootModel[Any]):
    root: Any


class DBSubnetGroupQuotaExceededFault(RootModel[Any]):
    root: Any


class DBSubnetQuotaExceededFault(RootModel[Any]):
    root: Any


class DBUpgradeDependencyFailureFault(RootModel[Any]):
    root: Any


class DomainNotFoundFault(RootModel[Any]):
    root: Any


class Double(RootModel[float]):
    root: float


class DoubleOptional(RootModel[float]):
    root: float


class DoubleRange(BaseModel):
    From: Optional[Double] = None
    To: Optional[Double] = None


class DoubleRangeList(RootModel[List[DoubleRange]]):
    root: List[DoubleRange]


class EventSubscriptionQuotaExceededFault(RootModel[Any]):
    root: Any


class GlobalClusterAlreadyExistsFault(RootModel[Any]):
    root: Any


class GlobalClusterIdentifier(
    RootModel[constr(pattern=r'[A-Za-z][0-9A-Za-z-:._]*', min_length=1, max_length=255)]
):
    root: constr(pattern=r'[A-Za-z][0-9A-Za-z-:._]*', min_length=1, max_length=255)


class GlobalClusterNotFoundFault(RootModel[Any]):
    root: Any


class GlobalClusterQuotaExceededFault(RootModel[Any]):
    root: Any


class InstanceQuotaExceededFault(RootModel[Any]):
    root: Any


class InsufficientDBClusterCapacityFault(RootModel[Any]):
    root: Any


class InsufficientDBInstanceCapacityFault(RootModel[Any]):
    root: Any


class InsufficientStorageClusterCapacityFault(RootModel[Any]):
    root: Any


class Integer(RootModel[int]):
    root: int


class IntegerOptional(RootModel[int]):
    root: int


class InvalidDBClusterEndpointStateFault(RootModel[Any]):
    root: Any


class InvalidDBClusterSnapshotStateFault(RootModel[Any]):
    root: Any


class InvalidDBClusterStateFault(RootModel[Any]):
    root: Any


class InvalidDBInstanceStateFault(RootModel[Any]):
    root: Any


class InvalidDBParameterGroupStateFault(RootModel[Any]):
    root: Any


class InvalidDBSecurityGroupStateFault(RootModel[Any]):
    root: Any


class InvalidDBSnapshotStateFault(RootModel[Any]):
    root: Any


class InvalidDBSubnetGroupStateFault(RootModel[Any]):
    root: Any


class InvalidDBSubnetStateFault(RootModel[Any]):
    root: Any


class InvalidEventSubscriptionStateFault(RootModel[Any]):
    root: Any


class InvalidGlobalClusterStateFault(RootModel[Any]):
    root: Any


class InvalidRestoreFault(RootModel[Any]):
    root: Any


class InvalidSubnet(RootModel[Any]):
    root: Any


class InvalidVPCNetworkStateFault(RootModel[Any]):
    root: Any


class KMSKeyNotAccessibleFault(RootModel[Any]):
    root: Any


class OptionGroupNotFoundFault(RootModel[Any]):
    root: Any


class ProvisionedIopsNotAvailableInAZFault(RootModel[Any]):
    root: Any


class Range(BaseModel):
    From: Optional[Integer] = None
    Step: Optional[IntegerOptional] = None
    To: Optional[Integer] = None


class RangeList(RootModel[List[Range]]):
    root: List[Range]


class ResourceNotFoundFault(RootModel[Any]):
    root: Any


class SNSInvalidTopicFault(RootModel[Any]):
    root: Any


class SNSNoAuthorizationFault(RootModel[Any]):
    root: Any


class SNSTopicArnNotFoundFault(RootModel[Any]):
    root: Any


class ServerlessV2ScalingConfiguration(BaseModel):
    MaxCapacity: Optional[DoubleOptional] = None
    MinCapacity: Optional[DoubleOptional] = None


class ServerlessV2ScalingConfigurationInfo(BaseModel):
    MaxCapacity: Optional[DoubleOptional] = None
    MinCapacity: Optional[DoubleOptional] = None


class SharedSnapshotQuotaExceededFault(RootModel[Any]):
    root: Any


class SnapshotQuotaExceededFault(RootModel[Any]):
    root: Any


class SourceNotFoundFault(RootModel[Any]):
    root: Any


class SourceType(Enum):
    db_instance = 'db-instance'
    db_parameter_group = 'db-parameter-group'
    db_security_group = 'db-security-group'
    db_snapshot = 'db-snapshot'
    db_cluster = 'db-cluster'
    db_cluster_snapshot = 'db-cluster-snapshot'


class StorageQuotaExceededFault(RootModel[Any]):
    root: Any


class StorageTypeNotSupportedFault(RootModel[Any]):
    root: Any


class String(RootModel[str]):
    root: str


class StringList(RootModel[List[String]]):
    root: List[String]


class SubnetAlreadyInUse(RootModel[Any]):
    root: Any


class SubnetIdentifierList(RootModel[List[String]]):
    root: List[String]


class SubscriptionAlreadyExistFault(RootModel[Any]):
    root: Any


class SubscriptionCategoryNotFoundFault(RootModel[Any]):
    root: Any


class SubscriptionNotFoundFault(RootModel[Any]):
    root: Any


class TStamp(RootModel[datetime]):
    root: datetime


class Tag(BaseModel):
    Key: Optional[String] = None
    Value: Optional[String] = None


class TagList(RootModel[List[Tag]]):
    root: List[Tag]


class TagListMessage(BaseModel):
    TagList_1: Optional[TagList] = Field(None, alias='TagList')


class Timezone(BaseModel):
    TimezoneName: Optional[String] = None


class UpgradeTarget(BaseModel):
    AutoUpgrade: Optional[Boolean] = None
    Description: Optional[String] = None
    Engine: Optional[String] = None
    EngineVersion: Optional[String] = None
    IsMajorVersionUpgrade: Optional[Boolean] = None
    SupportsGlobalDatabases: Optional[BooleanOptional] = None


class ValidStorageOptions(BaseModel):
    IopsToStorageRatio: Optional[DoubleRangeList] = None
    ProvisionedIops: Optional[RangeList] = None
    StorageSize: Optional[RangeList] = None
    StorageType: Optional[String] = None


class ValidStorageOptionsList(RootModel[List[ValidStorageOptions]]):
    root: List[ValidStorageOptions]


class ValidUpgradeTargetList(RootModel[List[UpgradeTarget]]):
    root: List[UpgradeTarget]


class VpcSecurityGroupIdList(RootModel[List[String]]):
    root: List[String]


class VpcSecurityGroupMembership(BaseModel):
    Status: Optional[String] = None
    VpcSecurityGroupId: Optional[String] = None


class VpcSecurityGroupMembershipList(RootModel[List[VpcSecurityGroupMembership]]):
    root: List[VpcSecurityGroupMembership]


class Action(Enum):
    AddRoleToDBCluster = 'AddRoleToDBCluster'


class Version(Enum):
    field_2014_10_31 = '2014-10-31'


class Action4(Enum):
    AddSourceIdentifierToSubscription = 'AddSourceIdentifierToSubscription'


class Action8(Enum):
    AddTagsToResource = 'AddTagsToResource'


class Tags(RootModel[List[Tag]]):
    root: List[Tag]


class Action12(Enum):
    ApplyPendingMaintenanceAction = 'ApplyPendingMaintenanceAction'


class Action16(Enum):
    CopyDBClusterParameterGroup = 'CopyDBClusterParameterGroup'


class Action20(Enum):
    CopyDBClusterSnapshot = 'CopyDBClusterSnapshot'


class Action24(Enum):
    CopyDBParameterGroup = 'CopyDBParameterGroup'


class Action28(Enum):
    CreateDBCluster = 'CreateDBCluster'


class AvailabilityZones(RootModel[List[String]]):
    root: List[String]


class VpcSecurityGroupIds(RootModel[List[String]]):
    root: List[String]


class EnableCloudwatchLogsExports(RootModel[List[String]]):
    root: List[String]


class Action32(Enum):
    CreateDBClusterEndpoint = 'CreateDBClusterEndpoint'


class StaticMembers(RootModel[List[String]]):
    root: List[String]


class ExcludedMembers(RootModel[List[String]]):
    root: List[String]


class Action36(Enum):
    CreateDBClusterParameterGroup = 'CreateDBClusterParameterGroup'


class Action40(Enum):
    CreateDBClusterSnapshot = 'CreateDBClusterSnapshot'


class Action44(Enum):
    CreateDBInstance = 'CreateDBInstance'


class DBSecurityGroups(RootModel[List[String]]):
    root: List[String]


class Action48(Enum):
    CreateDBParameterGroup = 'CreateDBParameterGroup'


class Action52(Enum):
    CreateDBSubnetGroup = 'CreateDBSubnetGroup'


class SubnetIds(RootModel[List[String]]):
    root: List[String]


class Action56(Enum):
    CreateEventSubscription = 'CreateEventSubscription'


class EventCategories(RootModel[List[String]]):
    root: List[String]


class SourceIds(RootModel[List[String]]):
    root: List[String]


class Action60(Enum):
    CreateGlobalCluster = 'CreateGlobalCluster'


class Action64(Enum):
    DeleteDBCluster = 'DeleteDBCluster'


class Action68(Enum):
    DeleteDBClusterEndpoint = 'DeleteDBClusterEndpoint'


class Action72(Enum):
    DeleteDBClusterParameterGroup = 'DeleteDBClusterParameterGroup'


class Action76(Enum):
    DeleteDBClusterSnapshot = 'DeleteDBClusterSnapshot'


class Action80(Enum):
    DeleteDBInstance = 'DeleteDBInstance'


class Action84(Enum):
    DeleteDBParameterGroup = 'DeleteDBParameterGroup'


class Action88(Enum):
    DeleteDBSubnetGroup = 'DeleteDBSubnetGroup'


class Action92(Enum):
    DeleteEventSubscription = 'DeleteEventSubscription'


class Action96(Enum):
    DeleteGlobalCluster = 'DeleteGlobalCluster'


class Action100(Enum):
    DescribeDBClusterEndpoints = 'DescribeDBClusterEndpoints'


class Action104(Enum):
    DescribeDBClusterParameterGroups = 'DescribeDBClusterParameterGroups'


class Action108(Enum):
    DescribeDBClusterParameters = 'DescribeDBClusterParameters'


class Action112(Enum):
    DescribeDBClusterSnapshotAttributes = 'DescribeDBClusterSnapshotAttributes'


class Action116(Enum):
    DescribeDBClusterSnapshots = 'DescribeDBClusterSnapshots'


class Action120(Enum):
    DescribeDBClusters = 'DescribeDBClusters'


class Action124(Enum):
    DescribeDBEngineVersions = 'DescribeDBEngineVersions'


class Action128(Enum):
    DescribeDBInstances = 'DescribeDBInstances'


class Action132(Enum):
    DescribeDBParameterGroups = 'DescribeDBParameterGroups'


class Action136(Enum):
    DescribeDBParameters = 'DescribeDBParameters'


class Action140(Enum):
    DescribeDBSubnetGroups = 'DescribeDBSubnetGroups'


class Action144(Enum):
    DescribeEngineDefaultClusterParameters = 'DescribeEngineDefaultClusterParameters'


class Action148(Enum):
    DescribeEngineDefaultParameters = 'DescribeEngineDefaultParameters'


class Action152(Enum):
    DescribeEventCategories = 'DescribeEventCategories'


class Action156(Enum):
    DescribeEventSubscriptions = 'DescribeEventSubscriptions'


class Action160(Enum):
    DescribeEvents = 'DescribeEvents'


class Action164(Enum):
    DescribeGlobalClusters = 'DescribeGlobalClusters'


class Action168(Enum):
    DescribeOrderableDBInstanceOptions = 'DescribeOrderableDBInstanceOptions'


class Action172(Enum):
    DescribePendingMaintenanceActions = 'DescribePendingMaintenanceActions'


class Action176(Enum):
    DescribeValidDBInstanceModifications = 'DescribeValidDBInstanceModifications'


class Action180(Enum):
    FailoverDBCluster = 'FailoverDBCluster'


class Action184(Enum):
    FailoverGlobalCluster = 'FailoverGlobalCluster'


class Action188(Enum):
    ListTagsForResource = 'ListTagsForResource'


class Action192(Enum):
    ModifyDBCluster = 'ModifyDBCluster'


class Action196(Enum):
    ModifyDBClusterEndpoint = 'ModifyDBClusterEndpoint'


class Action200(Enum):
    ModifyDBClusterParameterGroup = 'ModifyDBClusterParameterGroup'


class Action204(Enum):
    ModifyDBClusterSnapshotAttribute = 'ModifyDBClusterSnapshotAttribute'


class ValuesToAdd(RootModel[List[String]]):
    root: List[String]


class ValuesToRemove(RootModel[List[String]]):
    root: List[String]


class Action208(Enum):
    ModifyDBInstance = 'ModifyDBInstance'


class Action212(Enum):
    ModifyDBParameterGroup = 'ModifyDBParameterGroup'


class Action216(Enum):
    ModifyDBSubnetGroup = 'ModifyDBSubnetGroup'


class Action220(Enum):
    ModifyEventSubscription = 'ModifyEventSubscription'


class Action224(Enum):
    ModifyGlobalCluster = 'ModifyGlobalCluster'


class Action228(Enum):
    PromoteReadReplicaDBCluster = 'PromoteReadReplicaDBCluster'


class Action232(Enum):
    RebootDBInstance = 'RebootDBInstance'


class Action236(Enum):
    RemoveFromGlobalCluster = 'RemoveFromGlobalCluster'


class Action240(Enum):
    RemoveRoleFromDBCluster = 'RemoveRoleFromDBCluster'


class Action244(Enum):
    RemoveSourceIdentifierFromSubscription = 'RemoveSourceIdentifierFromSubscription'


class Action248(Enum):
    RemoveTagsFromResource = 'RemoveTagsFromResource'


class TagKeys(RootModel[List[String]]):
    root: List[String]


class Action252(Enum):
    ResetDBClusterParameterGroup = 'ResetDBClusterParameterGroup'


class Action256(Enum):
    ResetDBParameterGroup = 'ResetDBParameterGroup'


class Action260(Enum):
    RestoreDBClusterFromSnapshot = 'RestoreDBClusterFromSnapshot'


class Action264(Enum):
    RestoreDBClusterToPointInTime = 'RestoreDBClusterToPointInTime'


class Action268(Enum):
    StartDBCluster = 'StartDBCluster'


class Action272(Enum):
    StopDBCluster = 'StopDBCluster'


class AddRoleToDBClusterMessage(BaseModel):
    DBClusterIdentifier: String
    FeatureName: Optional[String] = None
    RoleArn: String


class AddSourceIdentifierToSubscriptionMessage(BaseModel):
    SourceIdentifier: String
    SubscriptionName: String


class AddTagsToResourceMessage(BaseModel):
    ResourceName: String
    Tags: TagList


class ApplyPendingMaintenanceActionMessage(BaseModel):
    ApplyAction: String
    OptInType: String
    ResourceIdentifier: String


class AttributeValueList(RootModel[List[String]]):
    root: List[String]


class AvailabilityZone(BaseModel):
    Name: Optional[String] = None


class AvailabilityZoneList(RootModel[List[AvailabilityZone]]):
    root: List[AvailabilityZone]


class CharacterSet(BaseModel):
    CharacterSetDescription: Optional[String] = None
    CharacterSetName: Optional[String] = None


class CopyDBClusterParameterGroupMessage(BaseModel):
    SourceDBClusterParameterGroupIdentifier: String
    Tags: Optional[TagList] = None
    TargetDBClusterParameterGroupDescription: String
    TargetDBClusterParameterGroupIdentifier: String


class CopyDBClusterSnapshotMessage(BaseModel):
    CopyTags: Optional[BooleanOptional] = None
    KmsKeyId: Optional[String] = None
    PreSignedUrl: Optional[String] = None
    SourceDBClusterSnapshotIdentifier: String
    Tags: Optional[TagList] = None
    TargetDBClusterSnapshotIdentifier: String


class CopyDBParameterGroupMessage(BaseModel):
    SourceDBParameterGroupIdentifier: String
    Tags: Optional[TagList] = None
    TargetDBParameterGroupDescription: String
    TargetDBParameterGroupIdentifier: String


class CreateDBClusterEndpointMessage(BaseModel):
    DBClusterEndpointIdentifier: String
    DBClusterIdentifier: String
    EndpointType: String
    ExcludedMembers: Optional[StringList] = None
    StaticMembers: Optional[StringList] = None
    Tags: Optional[TagList] = None


class CreateDBClusterEndpointOutput(BaseModel):
    CustomEndpointType: Optional[String] = None
    DBClusterEndpointArn: Optional[String] = None
    DBClusterEndpointIdentifier: Optional[String] = None
    DBClusterEndpointResourceIdentifier: Optional[String] = None
    DBClusterIdentifier: Optional[String] = None
    Endpoint: Optional[String] = None
    EndpointType: Optional[String] = None
    ExcludedMembers: Optional[StringList] = None
    StaticMembers: Optional[StringList] = None
    Status: Optional[String] = None


class CreateDBClusterParameterGroupMessage(BaseModel):
    DBClusterParameterGroupName: String
    DBParameterGroupFamily: String
    Description: String
    Tags: Optional[TagList] = None


class CreateDBClusterSnapshotMessage(BaseModel):
    DBClusterIdentifier: String
    DBClusterSnapshotIdentifier: String
    Tags: Optional[TagList] = None


class CreateDBParameterGroupMessage(BaseModel):
    DBParameterGroupFamily: String
    DBParameterGroupName: String
    Description: String
    Tags: Optional[TagList] = None


class CreateDBSubnetGroupMessage(BaseModel):
    DBSubnetGroupDescription: String
    DBSubnetGroupName: String
    SubnetIds: SubnetIdentifierList
    Tags: Optional[TagList] = None


class CreateGlobalClusterMessage(BaseModel):
    DeletionProtection: Optional[BooleanOptional] = None
    Engine: Optional[String] = None
    EngineVersion: Optional[String] = None
    GlobalClusterIdentifier_1: GlobalClusterIdentifier = Field(
        ..., alias='GlobalClusterIdentifier'
    )
    SourceDBClusterIdentifier: Optional[String] = None
    StorageEncrypted: Optional[BooleanOptional] = None


class DBClusterEndpoint(BaseModel):
    CustomEndpointType: Optional[String] = None
    DBClusterEndpointArn: Optional[String] = None
    DBClusterEndpointIdentifier: Optional[String] = None
    DBClusterEndpointResourceIdentifier: Optional[String] = None
    DBClusterIdentifier: Optional[String] = None
    Endpoint: Optional[String] = None
    EndpointType: Optional[String] = None
    ExcludedMembers: Optional[StringList] = None
    StaticMembers: Optional[StringList] = None
    Status: Optional[String] = None


class DBClusterEndpointList(RootModel[List[DBClusterEndpoint]]):
    root: List[DBClusterEndpoint]


class DBClusterEndpointMessage(BaseModel):
    DBClusterEndpoints: Optional[DBClusterEndpointList] = None
    Marker: Optional[String] = None


class DBClusterMember(BaseModel):
    DBClusterParameterGroupStatus: Optional[String] = None
    DBInstanceIdentifier: Optional[String] = None
    IsClusterWriter: Optional[Boolean] = None
    PromotionTier: Optional[IntegerOptional] = None


class DBClusterMemberList(RootModel[List[DBClusterMember]]):
    root: List[DBClusterMember]


class DBClusterOptionGroupStatus(BaseModel):
    DBClusterOptionGroupName: Optional[String] = None
    Status: Optional[String] = None


class DBClusterParameterGroup(BaseModel):
    DBClusterParameterGroupArn: Optional[String] = None
    DBClusterParameterGroupName: Optional[String] = None
    DBParameterGroupFamily: Optional[String] = None
    Description: Optional[String] = None


class DBClusterParameterGroupList(RootModel[List[DBClusterParameterGroup]]):
    root: List[DBClusterParameterGroup]


class DBClusterParameterGroupNameMessage(BaseModel):
    DBClusterParameterGroupName: Optional[String] = None


class DBClusterParameterGroupsMessage(BaseModel):
    DBClusterParameterGroups: Optional[DBClusterParameterGroupList] = None
    Marker: Optional[String] = None


class DBClusterRole(BaseModel):
    FeatureName: Optional[String] = None
    RoleArn: Optional[String] = None
    Status: Optional[String] = None


class DBClusterRoles(RootModel[List[DBClusterRole]]):
    root: List[DBClusterRole]


class DBClusterSnapshot(BaseModel):
    AllocatedStorage: Optional[Integer] = None
    AvailabilityZones_1: Optional[AvailabilityZones] = Field(
        None, alias='AvailabilityZones'
    )
    ClusterCreateTime: Optional[TStamp] = None
    DBClusterIdentifier: Optional[String] = None
    DBClusterSnapshotArn: Optional[String] = None
    DBClusterSnapshotIdentifier: Optional[String] = None
    Engine: Optional[String] = None
    EngineVersion: Optional[String] = None
    IAMDatabaseAuthenticationEnabled: Optional[Boolean] = None
    KmsKeyId: Optional[String] = None
    LicenseModel: Optional[String] = None
    MasterUsername: Optional[String] = None
    PercentProgress: Optional[Integer] = None
    Port: Optional[Integer] = None
    SnapshotCreateTime: Optional[TStamp] = None
    SnapshotType: Optional[String] = None
    SourceDBClusterSnapshotArn: Optional[String] = None
    Status: Optional[String] = None
    StorageEncrypted: Optional[Boolean] = None
    VpcId: Optional[String] = None


class DBClusterSnapshotAttribute(BaseModel):
    AttributeName: Optional[String] = None
    AttributeValues: Optional[AttributeValueList] = None


class DBClusterSnapshotAttributeList(RootModel[List[DBClusterSnapshotAttribute]]):
    root: List[DBClusterSnapshotAttribute]


class DBClusterSnapshotAttributesResult(BaseModel):
    DBClusterSnapshotAttributes: Optional[DBClusterSnapshotAttributeList] = None
    DBClusterSnapshotIdentifier: Optional[String] = None


class DBClusterSnapshotList(RootModel[List[DBClusterSnapshot]]):
    root: List[DBClusterSnapshot]


class DBClusterSnapshotMessage(BaseModel):
    DBClusterSnapshots: Optional[DBClusterSnapshotList] = None
    Marker: Optional[String] = None


class DBInstanceStatusInfo(BaseModel):
    Message: Optional[String] = None
    Normal: Optional[Boolean] = None
    Status: Optional[String] = None
    StatusType: Optional[String] = None


class DBInstanceStatusInfoList(RootModel[List[DBInstanceStatusInfo]]):
    root: List[DBInstanceStatusInfo]


class DBParameterGroup(BaseModel):
    DBParameterGroupArn: Optional[String] = None
    DBParameterGroupFamily: Optional[String] = None
    DBParameterGroupName: Optional[String] = None
    Description: Optional[String] = None


class DBParameterGroupList(RootModel[List[DBParameterGroup]]):
    root: List[DBParameterGroup]


class DBParameterGroupNameMessage(BaseModel):
    DBParameterGroupName: Optional[String] = None


class DBParameterGroupStatus(BaseModel):
    DBParameterGroupName: Optional[String] = None
    ParameterApplyStatus: Optional[String] = None


class DBParameterGroupStatusList(RootModel[List[DBParameterGroupStatus]]):
    root: List[DBParameterGroupStatus]


class DBParameterGroupsMessage(BaseModel):
    DBParameterGroups: Optional[DBParameterGroupList] = None
    Marker: Optional[String] = None


class DBSecurityGroupMembership(BaseModel):
    DBSecurityGroupName: Optional[String] = None
    Status: Optional[String] = None


class DBSecurityGroupMembershipList(RootModel[List[DBSecurityGroupMembership]]):
    root: List[DBSecurityGroupMembership]


class DBSecurityGroupNameList(RootModel[List[String]]):
    root: List[String]


class DeleteDBClusterEndpointMessage(BaseModel):
    DBClusterEndpointIdentifier: String


class DeleteDBClusterEndpointOutput(BaseModel):
    CustomEndpointType: Optional[String] = None
    DBClusterEndpointArn: Optional[String] = None
    DBClusterEndpointIdentifier: Optional[String] = None
    DBClusterEndpointResourceIdentifier: Optional[String] = None
    DBClusterIdentifier: Optional[String] = None
    Endpoint: Optional[String] = None
    EndpointType: Optional[String] = None
    ExcludedMembers: Optional[StringList] = None
    StaticMembers: Optional[StringList] = None
    Status: Optional[String] = None


class DeleteDBClusterMessage(BaseModel):
    DBClusterIdentifier: String
    FinalDBSnapshotIdentifier: Optional[String] = None
    SkipFinalSnapshot: Optional[Boolean] = None


class DeleteDBClusterParameterGroupMessage(BaseModel):
    DBClusterParameterGroupName: String


class DeleteDBClusterSnapshotMessage(BaseModel):
    DBClusterSnapshotIdentifier: String


class DeleteDBClusterSnapshotResult(BaseModel):
    DBClusterSnapshot_1: Optional[DBClusterSnapshot] = Field(
        None, alias='DBClusterSnapshot'
    )


class DeleteDBInstanceMessage(BaseModel):
    DBInstanceIdentifier: String
    FinalDBSnapshotIdentifier: Optional[String] = None
    SkipFinalSnapshot: Optional[Boolean] = None


class DeleteDBParameterGroupMessage(BaseModel):
    DBParameterGroupName: String


class DeleteDBSubnetGroupMessage(BaseModel):
    DBSubnetGroupName: String


class DeleteEventSubscriptionMessage(BaseModel):
    SubscriptionName: String


class DeleteGlobalClusterMessage(BaseModel):
    GlobalClusterIdentifier_1: GlobalClusterIdentifier = Field(
        ..., alias='GlobalClusterIdentifier'
    )


class DescribeDBClusterSnapshotAttributesMessage(BaseModel):
    DBClusterSnapshotIdentifier: String


class DescribeDBClusterSnapshotAttributesResult(BaseModel):
    DBClusterSnapshotAttributesResult_1: Optional[DBClusterSnapshotAttributesResult] = (
        Field(None, alias='DBClusterSnapshotAttributesResult')
    )


class DescribeGlobalClustersMessage(BaseModel):
    GlobalClusterIdentifier_1: Optional[GlobalClusterIdentifier] = Field(
        None, alias='GlobalClusterIdentifier'
    )
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeValidDBInstanceModificationsMessage(BaseModel):
    DBInstanceIdentifier: String


class DomainMembership(BaseModel):
    Domain: Optional[String] = None
    FQDN: Optional[String] = None
    IAMRoleName: Optional[String] = None
    Status: Optional[String] = None


class DomainMembershipList(RootModel[List[DomainMembership]]):
    root: List[DomainMembership]


class Endpoint(BaseModel):
    Address: Optional[String] = None
    HostedZoneId: Optional[String] = None
    Port: Optional[Integer] = None


class EventCategoriesList(RootModel[List[String]]):
    root: List[String]


class EventCategoriesMap(BaseModel):
    EventCategories: Optional[EventCategoriesList] = None
    SourceType: Optional[String] = None


class EventCategoriesMapList(RootModel[List[EventCategoriesMap]]):
    root: List[EventCategoriesMap]


class EventCategoriesMessage(BaseModel):
    EventCategoriesMapList_1: Optional[EventCategoriesMapList] = Field(
        None, alias='EventCategoriesMapList'
    )


class FailoverDBClusterMessage(BaseModel):
    DBClusterIdentifier: Optional[String] = None
    TargetDBInstanceIdentifier: Optional[String] = None


class FailoverGlobalClusterMessage(BaseModel):
    GlobalClusterIdentifier_1: GlobalClusterIdentifier = Field(
        ..., alias='GlobalClusterIdentifier'
    )
    TargetDbClusterIdentifier: String


class FilterValueList(RootModel[List[String]]):
    root: List[String]


class KeyList(RootModel[List[String]]):
    root: List[String]


class LogTypeList(RootModel[List[String]]):
    root: List[String]


class ModifyDBClusterEndpointMessage(BaseModel):
    DBClusterEndpointIdentifier: String
    EndpointType: Optional[String] = None
    ExcludedMembers: Optional[StringList] = None
    StaticMembers: Optional[StringList] = None


class ModifyDBClusterEndpointOutput(BaseModel):
    CustomEndpointType: Optional[String] = None
    DBClusterEndpointArn: Optional[String] = None
    DBClusterEndpointIdentifier: Optional[String] = None
    DBClusterEndpointResourceIdentifier: Optional[String] = None
    DBClusterIdentifier: Optional[String] = None
    Endpoint: Optional[String] = None
    EndpointType: Optional[String] = None
    ExcludedMembers: Optional[StringList] = None
    StaticMembers: Optional[StringList] = None
    Status: Optional[String] = None


class ModifyDBClusterSnapshotAttributeMessage(BaseModel):
    AttributeName: String
    DBClusterSnapshotIdentifier: String
    ValuesToAdd: Optional[AttributeValueList] = None
    ValuesToRemove: Optional[AttributeValueList] = None


class ModifyDBClusterSnapshotAttributeResult(BaseModel):
    DBClusterSnapshotAttributesResult_1: Optional[DBClusterSnapshotAttributesResult] = (
        Field(None, alias='DBClusterSnapshotAttributesResult')
    )


class ModifyDBSubnetGroupMessage(BaseModel):
    DBSubnetGroupDescription: Optional[String] = None
    DBSubnetGroupName: String
    SubnetIds: SubnetIdentifierList


class ModifyEventSubscriptionMessage(BaseModel):
    Enabled: Optional[BooleanOptional] = None
    EventCategories: Optional[EventCategoriesList] = None
    SnsTopicArn: Optional[String] = None
    SourceType: Optional[String] = None
    SubscriptionName: String


class ModifyGlobalClusterMessage(BaseModel):
    AllowMajorVersionUpgrade: Optional[BooleanOptional] = None
    DeletionProtection: Optional[BooleanOptional] = None
    EngineVersion: Optional[String] = None
    GlobalClusterIdentifier_1: GlobalClusterIdentifier = Field(
        ..., alias='GlobalClusterIdentifier'
    )
    NewGlobalClusterIdentifier: Optional[GlobalClusterIdentifier] = None


class OptionGroupMembership(BaseModel):
    OptionGroupName: Optional[String] = None
    Status: Optional[String] = None


class OptionGroupMembershipList(RootModel[List[OptionGroupMembership]]):
    root: List[OptionGroupMembership]


class OrderableDBInstanceOption(BaseModel):
    AvailabilityZones: Optional[AvailabilityZoneList] = None
    DBInstanceClass: Optional[String] = None
    Engine: Optional[String] = None
    EngineVersion: Optional[String] = None
    LicenseModel: Optional[String] = None
    MaxIopsPerDbInstance: Optional[IntegerOptional] = None
    MaxIopsPerGib: Optional[DoubleOptional] = None
    MaxStorageSize: Optional[IntegerOptional] = None
    MinIopsPerDbInstance: Optional[IntegerOptional] = None
    MinIopsPerGib: Optional[DoubleOptional] = None
    MinStorageSize: Optional[IntegerOptional] = None
    MultiAZCapable: Optional[Boolean] = None
    ReadReplicaCapable: Optional[Boolean] = None
    StorageType: Optional[String] = None
    SupportsEnhancedMonitoring: Optional[Boolean] = None
    SupportsGlobalDatabases: Optional[Boolean] = None
    SupportsIAMDatabaseAuthentication: Optional[Boolean] = None
    SupportsIops: Optional[Boolean] = None
    SupportsPerformanceInsights: Optional[Boolean] = None
    SupportsStorageEncryption: Optional[Boolean] = None
    Vpc: Optional[Boolean] = None


class OrderableDBInstanceOptionsList(RootModel[List[OrderableDBInstanceOption]]):
    root: List[OrderableDBInstanceOption]


class OrderableDBInstanceOptionsMessage(BaseModel):
    Marker: Optional[String] = None
    OrderableDBInstanceOptions: Optional[OrderableDBInstanceOptionsList] = None


class Parameter(BaseModel):
    AllowedValues: Optional[String] = None
    ApplyMethod_1: Optional[ApplyMethod] = Field(None, alias='ApplyMethod')
    ApplyType: Optional[String] = None
    DataType: Optional[String] = None
    Description: Optional[String] = None
    IsModifiable: Optional[Boolean] = None
    MinimumEngineVersion: Optional[String] = None
    ParameterName: Optional[String] = None
    ParameterValue: Optional[String] = None
    Source: Optional[String] = None


class ParametersList(RootModel[List[Parameter]]):
    root: List[Parameter]


class PendingCloudwatchLogsExports(BaseModel):
    LogTypesToDisable: Optional[LogTypeList] = None
    LogTypesToEnable: Optional[LogTypeList] = None


class PendingMaintenanceAction(BaseModel):
    Action: Optional[String] = None
    AutoAppliedAfterDate: Optional[TStamp] = None
    CurrentApplyDate: Optional[TStamp] = None
    Description: Optional[String] = None
    ForcedApplyDate: Optional[TStamp] = None
    OptInStatus: Optional[String] = None


class PendingMaintenanceActionDetails(RootModel[List[PendingMaintenanceAction]]):
    root: List[PendingMaintenanceAction]


class PendingModifiedValues(BaseModel):
    AllocatedStorage: Optional[IntegerOptional] = None
    BackupRetentionPeriod: Optional[IntegerOptional] = None
    CACertificateIdentifier: Optional[String] = None
    DBInstanceClass: Optional[String] = None
    DBInstanceIdentifier: Optional[String] = None
    DBSubnetGroupName: Optional[String] = None
    EngineVersion: Optional[String] = None
    Iops: Optional[IntegerOptional] = None
    LicenseModel: Optional[String] = None
    MasterUserPassword: Optional[String] = None
    MultiAZ: Optional[BooleanOptional] = None
    PendingCloudwatchLogsExports_1: Optional[PendingCloudwatchLogsExports] = Field(
        None, alias='PendingCloudwatchLogsExports'
    )
    Port: Optional[IntegerOptional] = None
    StorageType: Optional[String] = None


class PromoteReadReplicaDBClusterMessage(BaseModel):
    DBClusterIdentifier: String


class ReadReplicaDBClusterIdentifierList(RootModel[List[String]]):
    root: List[String]


class ReadReplicaDBInstanceIdentifierList(RootModel[List[String]]):
    root: List[String]


class ReadReplicaIdentifierList(RootModel[List[String]]):
    root: List[String]


class ReadersArnList(RootModel[List[String]]):
    root: List[String]


class RebootDBInstanceMessage(BaseModel):
    DBInstanceIdentifier: String
    ForceFailover: Optional[BooleanOptional] = None


class RemoveFromGlobalClusterMessage(BaseModel):
    DbClusterIdentifier: String
    GlobalClusterIdentifier_1: GlobalClusterIdentifier = Field(
        ..., alias='GlobalClusterIdentifier'
    )


class RemoveRoleFromDBClusterMessage(BaseModel):
    DBClusterIdentifier: String
    FeatureName: Optional[String] = None
    RoleArn: String


class RemoveSourceIdentifierFromSubscriptionMessage(BaseModel):
    SourceIdentifier: String
    SubscriptionName: String


class RemoveTagsFromResourceMessage(BaseModel):
    ResourceName: String
    TagKeys: KeyList


class ResetDBClusterParameterGroupMessage(BaseModel):
    DBClusterParameterGroupName: String
    Parameters: Optional[ParametersList] = None
    ResetAllParameters: Optional[Boolean] = None


class ResetDBParameterGroupMessage(BaseModel):
    DBParameterGroupName: String
    Parameters: Optional[ParametersList] = None
    ResetAllParameters: Optional[Boolean] = None


class ResourcePendingMaintenanceActions(BaseModel):
    PendingMaintenanceActionDetails_1: Optional[PendingMaintenanceActionDetails] = (
        Field(None, alias='PendingMaintenanceActionDetails')
    )
    ResourceIdentifier: Optional[String] = None


class RestoreDBClusterFromSnapshotMessage(BaseModel):
    AvailabilityZones_1: Optional[AvailabilityZones] = Field(
        None, alias='AvailabilityZones'
    )
    CopyTagsToSnapshot: Optional[BooleanOptional] = None
    DBClusterIdentifier: String
    DBClusterParameterGroupName: Optional[String] = None
    DBSubnetGroupName: Optional[String] = None
    DatabaseName: Optional[String] = None
    DeletionProtection: Optional[BooleanOptional] = None
    EnableCloudwatchLogsExports: Optional[LogTypeList] = None
    EnableIAMDatabaseAuthentication: Optional[BooleanOptional] = None
    Engine: String
    EngineVersion: Optional[String] = None
    KmsKeyId: Optional[String] = None
    OptionGroupName: Optional[String] = None
    Port: Optional[IntegerOptional] = None
    ServerlessV2ScalingConfiguration_1: Optional[ServerlessV2ScalingConfiguration] = (
        Field(None, alias='ServerlessV2ScalingConfiguration')
    )
    SnapshotIdentifier: String
    Tags: Optional[TagList] = None
    VpcSecurityGroupIds: Optional[VpcSecurityGroupIdList] = None


class RestoreDBClusterToPointInTimeMessage(BaseModel):
    DBClusterIdentifier: String
    DBClusterParameterGroupName: Optional[String] = None
    DBSubnetGroupName: Optional[String] = None
    DeletionProtection: Optional[BooleanOptional] = None
    EnableCloudwatchLogsExports: Optional[LogTypeList] = None
    EnableIAMDatabaseAuthentication: Optional[BooleanOptional] = None
    KmsKeyId: Optional[String] = None
    OptionGroupName: Optional[String] = None
    Port: Optional[IntegerOptional] = None
    RestoreToTime: Optional[TStamp] = None
    RestoreType: Optional[String] = None
    ServerlessV2ScalingConfiguration_1: Optional[ServerlessV2ScalingConfiguration] = (
        Field(None, alias='ServerlessV2ScalingConfiguration')
    )
    SourceDBClusterIdentifier: String
    Tags: Optional[TagList] = None
    UseLatestRestorableTime: Optional[Boolean] = None
    VpcSecurityGroupIds: Optional[VpcSecurityGroupIdList] = None


class SourceIdsList(RootModel[List[String]]):
    root: List[String]


class StartDBClusterMessage(BaseModel):
    DBClusterIdentifier: String


class StopDBClusterMessage(BaseModel):
    DBClusterIdentifier: String


class Subnet(BaseModel):
    SubnetAvailabilityZone: Optional[AvailabilityZone] = None
    SubnetIdentifier: Optional[String] = None
    SubnetStatus: Optional[String] = None


class SubnetList(RootModel[List[Subnet]]):
    root: List[Subnet]


class SupportedCharacterSetsList(RootModel[List[CharacterSet]]):
    root: List[CharacterSet]


class SupportedTimezonesList(RootModel[List[Timezone]]):
    root: List[Timezone]


class ValidDBInstanceModificationsMessage(BaseModel):
    Storage: Optional[ValidStorageOptionsList] = None


class CloudwatchLogsExportConfiguration(BaseModel):
    DisableLogTypes: Optional[LogTypeList] = None
    EnableLogTypes: Optional[LogTypeList] = None


class Parameters(RootModel[List[Parameter]]):
    root: List[Parameter]


class ApplyPendingMaintenanceActionResult(BaseModel):
    ResourcePendingMaintenanceActions_1: Optional[ResourcePendingMaintenanceActions] = (
        Field(None, alias='ResourcePendingMaintenanceActions')
    )


class ClusterPendingModifiedValues(BaseModel):
    AllocatedStorage: Optional[IntegerOptional] = None
    BackupRetentionPeriod: Optional[IntegerOptional] = None
    DBClusterIdentifier: Optional[String] = None
    EngineVersion: Optional[String] = None
    IAMDatabaseAuthenticationEnabled: Optional[BooleanOptional] = None
    Iops: Optional[IntegerOptional] = None
    PendingCloudwatchLogsExports_1: Optional[PendingCloudwatchLogsExports] = Field(
        None, alias='PendingCloudwatchLogsExports'
    )


class CopyDBClusterParameterGroupResult(BaseModel):
    DBClusterParameterGroup_1: Optional[DBClusterParameterGroup] = Field(
        None, alias='DBClusterParameterGroup'
    )


class CopyDBClusterSnapshotResult(BaseModel):
    DBClusterSnapshot_1: Optional[DBClusterSnapshot] = Field(
        None, alias='DBClusterSnapshot'
    )


class CopyDBParameterGroupResult(BaseModel):
    DBParameterGroup_1: Optional[DBParameterGroup] = Field(
        None, alias='DBParameterGroup'
    )


class CreateDBClusterMessage(BaseModel):
    AvailabilityZones_1: Optional[AvailabilityZones] = Field(
        None, alias='AvailabilityZones'
    )
    BackupRetentionPeriod: Optional[IntegerOptional] = None
    CharacterSetName: Optional[String] = None
    CopyTagsToSnapshot: Optional[BooleanOptional] = None
    DBClusterIdentifier: String
    DBClusterParameterGroupName: Optional[String] = None
    DBSubnetGroupName: Optional[String] = None
    DatabaseName: Optional[String] = None
    DeletionProtection: Optional[BooleanOptional] = None
    EnableCloudwatchLogsExports: Optional[LogTypeList] = None
    EnableIAMDatabaseAuthentication: Optional[BooleanOptional] = None
    Engine: String
    EngineVersion: Optional[String] = None
    GlobalClusterIdentifier_1: Optional[GlobalClusterIdentifier] = Field(
        None, alias='GlobalClusterIdentifier'
    )
    KmsKeyId: Optional[String] = None
    MasterUserPassword: Optional[String] = None
    MasterUsername: Optional[String] = None
    OptionGroupName: Optional[String] = None
    Port: Optional[IntegerOptional] = None
    PreSignedUrl: Optional[String] = None
    PreferredBackupWindow: Optional[String] = None
    PreferredMaintenanceWindow: Optional[String] = None
    ReplicationSourceIdentifier: Optional[String] = None
    ServerlessV2ScalingConfiguration_1: Optional[ServerlessV2ScalingConfiguration] = (
        Field(None, alias='ServerlessV2ScalingConfiguration')
    )
    StorageEncrypted: Optional[BooleanOptional] = None
    Tags: Optional[TagList] = None
    VpcSecurityGroupIds: Optional[VpcSecurityGroupIdList] = None


class CreateDBClusterParameterGroupResult(BaseModel):
    DBClusterParameterGroup_1: Optional[DBClusterParameterGroup] = Field(
        None, alias='DBClusterParameterGroup'
    )


class CreateDBClusterSnapshotResult(BaseModel):
    DBClusterSnapshot_1: Optional[DBClusterSnapshot] = Field(
        None, alias='DBClusterSnapshot'
    )


class CreateDBInstanceMessage(BaseModel):
    AllocatedStorage: Optional[IntegerOptional] = None
    AutoMinorVersionUpgrade: Optional[BooleanOptional] = None
    AvailabilityZone: Optional[String] = None
    BackupRetentionPeriod: Optional[IntegerOptional] = None
    CharacterSetName: Optional[String] = None
    CopyTagsToSnapshot: Optional[BooleanOptional] = None
    DBClusterIdentifier: String
    DBInstanceClass: String
    DBInstanceIdentifier: String
    DBName: Optional[String] = None
    DBParameterGroupName: Optional[String] = None
    DBSecurityGroups: Optional[DBSecurityGroupNameList] = None
    DBSubnetGroupName: Optional[String] = None
    DeletionProtection: Optional[BooleanOptional] = None
    Domain: Optional[String] = None
    DomainIAMRoleName: Optional[String] = None
    EnableCloudwatchLogsExports: Optional[LogTypeList] = None
    EnableIAMDatabaseAuthentication: Optional[BooleanOptional] = None
    EnablePerformanceInsights: Optional[BooleanOptional] = None
    Engine: String
    EngineVersion: Optional[String] = None
    Iops: Optional[IntegerOptional] = None
    KmsKeyId: Optional[String] = None
    LicenseModel: Optional[String] = None
    MasterUserPassword: Optional[String] = None
    MasterUsername: Optional[String] = None
    MonitoringInterval: Optional[IntegerOptional] = None
    MonitoringRoleArn: Optional[String] = None
    MultiAZ: Optional[BooleanOptional] = None
    OptionGroupName: Optional[String] = None
    PerformanceInsightsKMSKeyId: Optional[String] = None
    Port: Optional[IntegerOptional] = None
    PreferredBackupWindow: Optional[String] = None
    PreferredMaintenanceWindow: Optional[String] = None
    PromotionTier: Optional[IntegerOptional] = None
    PubliclyAccessible: Optional[BooleanOptional] = None
    StorageEncrypted: Optional[BooleanOptional] = None
    StorageType: Optional[String] = None
    Tags: Optional[TagList] = None
    TdeCredentialArn: Optional[String] = None
    TdeCredentialPassword: Optional[String] = None
    Timezone: Optional[String] = None
    VpcSecurityGroupIds: Optional[VpcSecurityGroupIdList] = None


class CreateDBParameterGroupResult(BaseModel):
    DBParameterGroup_1: Optional[DBParameterGroup] = Field(
        None, alias='DBParameterGroup'
    )


class CreateEventSubscriptionMessage(BaseModel):
    Enabled: Optional[BooleanOptional] = None
    EventCategories: Optional[EventCategoriesList] = None
    SnsTopicArn: String
    SourceIds: Optional[SourceIdsList] = None
    SourceType: Optional[String] = None
    SubscriptionName: String
    Tags: Optional[TagList] = None


class DBClusterOptionGroupMemberships(RootModel[List[DBClusterOptionGroupStatus]]):
    root: List[DBClusterOptionGroupStatus]


class DBClusterParameterGroupDetails(BaseModel):
    Marker: Optional[String] = None
    Parameters: Optional[ParametersList] = None


class DBEngineVersion(BaseModel):
    DBEngineDescription: Optional[String] = None
    DBEngineVersionDescription: Optional[String] = None
    DBParameterGroupFamily: Optional[String] = None
    DefaultCharacterSet: Optional[CharacterSet] = None
    Engine: Optional[String] = None
    EngineVersion: Optional[String] = None
    ExportableLogTypes: Optional[LogTypeList] = None
    SupportedCharacterSets: Optional[SupportedCharacterSetsList] = None
    SupportedTimezones: Optional[SupportedTimezonesList] = None
    SupportsGlobalDatabases: Optional[Boolean] = None
    SupportsLogExportsToCloudwatchLogs: Optional[Boolean] = None
    SupportsReadReplica: Optional[Boolean] = None
    ValidUpgradeTarget: Optional[ValidUpgradeTargetList] = None


class DBEngineVersionList(RootModel[List[DBEngineVersion]]):
    root: List[DBEngineVersion]


class DBEngineVersionMessage(BaseModel):
    DBEngineVersions: Optional[DBEngineVersionList] = None
    Marker: Optional[String] = None


class DBParameterGroupDetails(BaseModel):
    Marker: Optional[String] = None
    Parameters: Optional[ParametersList] = None


class DBSubnetGroup(BaseModel):
    DBSubnetGroupArn: Optional[String] = None
    DBSubnetGroupDescription: Optional[String] = None
    DBSubnetGroupName: Optional[String] = None
    SubnetGroupStatus: Optional[String] = None
    Subnets: Optional[SubnetList] = None
    VpcId: Optional[String] = None


class DBSubnetGroups(RootModel[List[DBSubnetGroup]]):
    root: List[DBSubnetGroup]


class DescribeValidDBInstanceModificationsResult(BaseModel):
    ValidDBInstanceModificationsMessage_1: Optional[
        ValidDBInstanceModificationsMessage
    ] = Field(None, alias='ValidDBInstanceModificationsMessage')


class EngineDefaults(BaseModel):
    DBParameterGroupFamily: Optional[String] = None
    Marker: Optional[String] = None
    Parameters: Optional[ParametersList] = None


class Event(BaseModel):
    Date: Optional[TStamp] = None
    EventCategories: Optional[EventCategoriesList] = None
    Message: Optional[String] = None
    SourceArn: Optional[String] = None
    SourceIdentifier: Optional[String] = None
    SourceType_1: Optional[SourceType] = Field(None, alias='SourceType')


class EventList(RootModel[List[Event]]):
    root: List[Event]


class EventSubscription(BaseModel):
    CustSubscriptionId: Optional[String] = None
    CustomerAwsId: Optional[String] = None
    Enabled: Optional[Boolean] = None
    EventCategoriesList_1: Optional[EventCategoriesList] = Field(
        None, alias='EventCategoriesList'
    )
    EventSubscriptionArn: Optional[String] = None
    SnsTopicArn: Optional[String] = None
    SourceIdsList_1: Optional[SourceIdsList] = Field(None, alias='SourceIdsList')
    SourceType: Optional[String] = None
    Status: Optional[String] = None
    SubscriptionCreationTime: Optional[String] = None


class EventSubscriptionsList(RootModel[List[EventSubscription]]):
    root: List[EventSubscription]


class EventSubscriptionsMessage(BaseModel):
    EventSubscriptionsList_1: Optional[EventSubscriptionsList] = Field(
        None, alias='EventSubscriptionsList'
    )
    Marker: Optional[String] = None


class EventsMessage(BaseModel):
    Events: Optional[EventList] = None
    Marker: Optional[String] = None


class Filter(BaseModel):
    Name: String
    Values: FilterValueList


class FilterList(RootModel[List[Filter]]):
    root: List[Filter]


class GlobalClusterMember(BaseModel):
    DBClusterArn: Optional[String] = None
    IsWriter: Optional[Boolean] = None
    Readers: Optional[ReadersArnList] = None


class GlobalClusterMemberList(RootModel[List[GlobalClusterMember]]):
    root: List[GlobalClusterMember]


class ListTagsForResourceMessage(BaseModel):
    Filters: Optional[FilterList] = None
    ResourceName: String


class ModifyDBClusterMessage(BaseModel):
    AllowMajorVersionUpgrade: Optional[Boolean] = None
    ApplyImmediately: Optional[Boolean] = None
    BackupRetentionPeriod: Optional[IntegerOptional] = None
    CloudwatchLogsExportConfiguration_1: Optional[CloudwatchLogsExportConfiguration] = (
        Field(None, alias='CloudwatchLogsExportConfiguration')
    )
    CopyTagsToSnapshot: Optional[BooleanOptional] = None
    DBClusterIdentifier: String
    DBClusterParameterGroupName: Optional[String] = None
    DBInstanceParameterGroupName: Optional[String] = None
    DeletionProtection: Optional[BooleanOptional] = None
    EnableIAMDatabaseAuthentication: Optional[BooleanOptional] = None
    EngineVersion: Optional[String] = None
    MasterUserPassword: Optional[String] = None
    NewDBClusterIdentifier: Optional[String] = None
    OptionGroupName: Optional[String] = None
    Port: Optional[IntegerOptional] = None
    PreferredBackupWindow: Optional[String] = None
    PreferredMaintenanceWindow: Optional[String] = None
    ServerlessV2ScalingConfiguration_1: Optional[ServerlessV2ScalingConfiguration] = (
        Field(None, alias='ServerlessV2ScalingConfiguration')
    )
    VpcSecurityGroupIds: Optional[VpcSecurityGroupIdList] = None


class ModifyDBClusterParameterGroupMessage(BaseModel):
    DBClusterParameterGroupName: String
    Parameters: ParametersList


class ModifyDBInstanceMessage(BaseModel):
    AllocatedStorage: Optional[IntegerOptional] = None
    AllowMajorVersionUpgrade: Optional[Boolean] = None
    ApplyImmediately: Optional[Boolean] = None
    AutoMinorVersionUpgrade: Optional[BooleanOptional] = None
    BackupRetentionPeriod: Optional[IntegerOptional] = None
    CACertificateIdentifier: Optional[String] = None
    CloudwatchLogsExportConfiguration_1: Optional[CloudwatchLogsExportConfiguration] = (
        Field(None, alias='CloudwatchLogsExportConfiguration')
    )
    CopyTagsToSnapshot: Optional[BooleanOptional] = None
    DBInstanceClass: Optional[String] = None
    DBInstanceIdentifier: String
    DBParameterGroupName: Optional[String] = None
    DBPortNumber: Optional[IntegerOptional] = None
    DBSecurityGroups: Optional[DBSecurityGroupNameList] = None
    DBSubnetGroupName: Optional[String] = None
    DeletionProtection: Optional[BooleanOptional] = None
    Domain: Optional[String] = None
    DomainIAMRoleName: Optional[String] = None
    EnableIAMDatabaseAuthentication: Optional[BooleanOptional] = None
    EnablePerformanceInsights: Optional[BooleanOptional] = None
    EngineVersion: Optional[String] = None
    Iops: Optional[IntegerOptional] = None
    LicenseModel: Optional[String] = None
    MasterUserPassword: Optional[String] = None
    MonitoringInterval: Optional[IntegerOptional] = None
    MonitoringRoleArn: Optional[String] = None
    MultiAZ: Optional[BooleanOptional] = None
    NewDBInstanceIdentifier: Optional[String] = None
    OptionGroupName: Optional[String] = None
    PerformanceInsightsKMSKeyId: Optional[String] = None
    PreferredBackupWindow: Optional[String] = None
    PreferredMaintenanceWindow: Optional[String] = None
    PromotionTier: Optional[IntegerOptional] = None
    PubliclyAccessible: Optional[BooleanOptional] = None
    StorageType: Optional[String] = None
    TdeCredentialArn: Optional[String] = None
    TdeCredentialPassword: Optional[String] = None
    VpcSecurityGroupIds: Optional[VpcSecurityGroupIdList] = None


class ModifyDBParameterGroupMessage(BaseModel):
    DBParameterGroupName: String
    Parameters: ParametersList


class ModifyDBSubnetGroupResult(BaseModel):
    DBSubnetGroup_1: Optional[DBSubnetGroup] = Field(None, alias='DBSubnetGroup')


class ModifyEventSubscriptionResult(BaseModel):
    EventSubscription_1: Optional[EventSubscription] = Field(
        None, alias='EventSubscription'
    )


class PendingMaintenanceActions(RootModel[List[ResourcePendingMaintenanceActions]]):
    root: List[ResourcePendingMaintenanceActions]


class PendingMaintenanceActionsMessage(BaseModel):
    Marker: Optional[String] = None
    PendingMaintenanceActions_1: Optional[PendingMaintenanceActions] = Field(
        None, alias='PendingMaintenanceActions'
    )


class RemoveSourceIdentifierFromSubscriptionResult(BaseModel):
    EventSubscription_1: Optional[EventSubscription] = Field(
        None, alias='EventSubscription'
    )


class Filters(RootModel[List[Filter]]):
    root: List[Filter]


class AddSourceIdentifierToSubscriptionResult(BaseModel):
    EventSubscription_1: Optional[EventSubscription] = Field(
        None, alias='EventSubscription'
    )


class CreateDBSubnetGroupResult(BaseModel):
    DBSubnetGroup_1: Optional[DBSubnetGroup] = Field(None, alias='DBSubnetGroup')


class CreateEventSubscriptionResult(BaseModel):
    EventSubscription_1: Optional[EventSubscription] = Field(
        None, alias='EventSubscription'
    )


class DBCluster(BaseModel):
    AllocatedStorage: Optional[IntegerOptional] = None
    AssociatedRoles: Optional[DBClusterRoles] = None
    AutomaticRestartTime: Optional[TStamp] = None
    AvailabilityZones_1: Optional[AvailabilityZones] = Field(
        None, alias='AvailabilityZones'
    )
    BackupRetentionPeriod: Optional[IntegerOptional] = None
    CharacterSetName: Optional[String] = None
    CloneGroupId: Optional[String] = None
    ClusterCreateTime: Optional[TStamp] = None
    CopyTagsToSnapshot: Optional[BooleanOptional] = None
    CrossAccountClone: Optional[BooleanOptional] = None
    DBClusterArn: Optional[String] = None
    DBClusterIdentifier: Optional[String] = None
    DBClusterMembers: Optional[DBClusterMemberList] = None
    DBClusterOptionGroupMemberships_1: Optional[DBClusterOptionGroupMemberships] = (
        Field(None, alias='DBClusterOptionGroupMemberships')
    )
    DBClusterParameterGroup: Optional[String] = None
    DBSubnetGroup: Optional[String] = None
    DatabaseName: Optional[String] = None
    DbClusterResourceId: Optional[String] = None
    DeletionProtection: Optional[BooleanOptional] = None
    EarliestRestorableTime: Optional[TStamp] = None
    EnabledCloudwatchLogsExports: Optional[LogTypeList] = None
    Endpoint: Optional[String] = None
    Engine: Optional[String] = None
    EngineVersion: Optional[String] = None
    GlobalClusterIdentifier_1: Optional[GlobalClusterIdentifier] = Field(
        None, alias='GlobalClusterIdentifier'
    )
    HostedZoneId: Optional[String] = None
    IAMDatabaseAuthenticationEnabled: Optional[Boolean] = None
    KmsKeyId: Optional[String] = None
    LatestRestorableTime: Optional[TStamp] = None
    MasterUsername: Optional[String] = None
    MultiAZ: Optional[Boolean] = None
    PendingModifiedValues: Optional[ClusterPendingModifiedValues] = None
    PercentProgress: Optional[String] = None
    Port: Optional[IntegerOptional] = None
    PreferredBackupWindow: Optional[String] = None
    PreferredMaintenanceWindow: Optional[String] = None
    ReadReplicaIdentifiers: Optional[ReadReplicaIdentifierList] = None
    ReaderEndpoint: Optional[String] = None
    ReplicationSourceIdentifier: Optional[String] = None
    ServerlessV2ScalingConfiguration: Optional[ServerlessV2ScalingConfigurationInfo] = (
        None
    )
    Status: Optional[String] = None
    StorageEncrypted: Optional[Boolean] = None
    VpcSecurityGroups: Optional[VpcSecurityGroupMembershipList] = None


class DBClusterList(RootModel[List[DBCluster]]):
    root: List[DBCluster]


class DBClusterMessage(BaseModel):
    DBClusters: Optional[DBClusterList] = None
    Marker: Optional[String] = None


class DBInstance(BaseModel):
    AllocatedStorage: Optional[Integer] = None
    AutoMinorVersionUpgrade: Optional[Boolean] = None
    AvailabilityZone: Optional[String] = None
    BackupRetentionPeriod: Optional[Integer] = None
    CACertificateIdentifier: Optional[String] = None
    CharacterSetName: Optional[String] = None
    CopyTagsToSnapshot: Optional[Boolean] = None
    DBClusterIdentifier: Optional[String] = None
    DBInstanceArn: Optional[String] = None
    DBInstanceClass: Optional[String] = None
    DBInstanceIdentifier: Optional[String] = None
    DBInstanceStatus: Optional[String] = None
    DBName: Optional[String] = None
    DBParameterGroups: Optional[DBParameterGroupStatusList] = None
    DBSecurityGroups: Optional[DBSecurityGroupMembershipList] = None
    DBSubnetGroup_1: Optional[DBSubnetGroup] = Field(None, alias='DBSubnetGroup')
    DbInstancePort: Optional[Integer] = None
    DbiResourceId: Optional[String] = None
    DeletionProtection: Optional[BooleanOptional] = None
    DomainMemberships: Optional[DomainMembershipList] = None
    EnabledCloudwatchLogsExports: Optional[LogTypeList] = None
    Endpoint_1: Optional[Endpoint] = Field(None, alias='Endpoint')
    Engine: Optional[String] = None
    EngineVersion: Optional[String] = None
    EnhancedMonitoringResourceArn: Optional[String] = None
    IAMDatabaseAuthenticationEnabled: Optional[Boolean] = None
    InstanceCreateTime: Optional[TStamp] = None
    Iops: Optional[IntegerOptional] = None
    KmsKeyId: Optional[String] = None
    LatestRestorableTime: Optional[TStamp] = None
    LicenseModel: Optional[String] = None
    MasterUsername: Optional[String] = None
    MonitoringInterval: Optional[IntegerOptional] = None
    MonitoringRoleArn: Optional[String] = None
    MultiAZ: Optional[Boolean] = None
    OptionGroupMemberships: Optional[OptionGroupMembershipList] = None
    PendingModifiedValues_1: Optional[PendingModifiedValues] = Field(
        None, alias='PendingModifiedValues'
    )
    PerformanceInsightsEnabled: Optional[BooleanOptional] = None
    PerformanceInsightsKMSKeyId: Optional[String] = None
    PreferredBackupWindow: Optional[String] = None
    PreferredMaintenanceWindow: Optional[String] = None
    PromotionTier: Optional[IntegerOptional] = None
    PubliclyAccessible: Optional[Boolean] = None
    ReadReplicaDBClusterIdentifiers: Optional[ReadReplicaDBClusterIdentifierList] = None
    ReadReplicaDBInstanceIdentifiers: Optional[ReadReplicaDBInstanceIdentifierList] = (
        None
    )
    ReadReplicaSourceDBInstanceIdentifier: Optional[String] = None
    SecondaryAvailabilityZone: Optional[String] = None
    StatusInfos: Optional[DBInstanceStatusInfoList] = None
    StorageEncrypted: Optional[Boolean] = None
    StorageType: Optional[String] = None
    TdeCredentialArn: Optional[String] = None
    Timezone: Optional[String] = None
    VpcSecurityGroups: Optional[VpcSecurityGroupMembershipList] = None


class DBInstanceList(RootModel[List[DBInstance]]):
    root: List[DBInstance]


class DBInstanceMessage(BaseModel):
    DBInstances: Optional[DBInstanceList] = None
    Marker: Optional[String] = None


class DBSubnetGroupMessage(BaseModel):
    DBSubnetGroups_1: Optional[DBSubnetGroups] = Field(None, alias='DBSubnetGroups')
    Marker: Optional[String] = None


class DeleteDBClusterResult(BaseModel):
    DBCluster_1: Optional[DBCluster] = Field(None, alias='DBCluster')


class DeleteDBInstanceResult(BaseModel):
    DBInstance_1: Optional[DBInstance] = Field(None, alias='DBInstance')


class DeleteEventSubscriptionResult(BaseModel):
    EventSubscription_1: Optional[EventSubscription] = Field(
        None, alias='EventSubscription'
    )


class DescribeDBClusterEndpointsMessage(BaseModel):
    DBClusterEndpointIdentifier: Optional[String] = None
    DBClusterIdentifier: Optional[String] = None
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeDBClusterParameterGroupsMessage(BaseModel):
    DBClusterParameterGroupName: Optional[String] = None
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeDBClusterParametersMessage(BaseModel):
    DBClusterParameterGroupName: String
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None
    Source: Optional[String] = None


class DescribeDBClusterSnapshotsMessage(BaseModel):
    DBClusterIdentifier: Optional[String] = None
    DBClusterSnapshotIdentifier: Optional[String] = None
    Filters: Optional[FilterList] = None
    IncludePublic: Optional[Boolean] = None
    IncludeShared: Optional[Boolean] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None
    SnapshotType: Optional[String] = None


class DescribeDBClustersMessage(BaseModel):
    DBClusterIdentifier: Optional[String] = None
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeDBEngineVersionsMessage(BaseModel):
    DBParameterGroupFamily: Optional[String] = None
    DefaultOnly: Optional[Boolean] = None
    Engine: Optional[String] = None
    EngineVersion: Optional[String] = None
    Filters: Optional[FilterList] = None
    ListSupportedCharacterSets: Optional[BooleanOptional] = None
    ListSupportedTimezones: Optional[BooleanOptional] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeDBInstancesMessage(BaseModel):
    DBInstanceIdentifier: Optional[String] = None
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeDBParameterGroupsMessage(BaseModel):
    DBParameterGroupName: Optional[String] = None
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeDBParametersMessage(BaseModel):
    DBParameterGroupName: String
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None
    Source: Optional[String] = None


class DescribeDBSubnetGroupsMessage(BaseModel):
    DBSubnetGroupName: Optional[String] = None
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeEngineDefaultClusterParametersMessage(BaseModel):
    DBParameterGroupFamily: String
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeEngineDefaultClusterParametersResult(BaseModel):
    EngineDefaults_1: Optional[EngineDefaults] = Field(None, alias='EngineDefaults')


class DescribeEngineDefaultParametersMessage(BaseModel):
    DBParameterGroupFamily: String
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None


class DescribeEngineDefaultParametersResult(BaseModel):
    EngineDefaults_1: Optional[EngineDefaults] = Field(None, alias='EngineDefaults')


class DescribeEventCategoriesMessage(BaseModel):
    Filters: Optional[FilterList] = None
    SourceType: Optional[String] = None


class DescribeEventSubscriptionsMessage(BaseModel):
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None
    SubscriptionName: Optional[String] = None


class DescribeEventsMessage(BaseModel):
    Duration: Optional[IntegerOptional] = None
    EndTime: Optional[TStamp] = None
    EventCategories: Optional[EventCategoriesList] = None
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None
    SourceIdentifier: Optional[String] = None
    SourceType_1: Optional[SourceType] = Field(None, alias='SourceType')
    StartTime: Optional[TStamp] = None


class DescribeOrderableDBInstanceOptionsMessage(BaseModel):
    DBInstanceClass: Optional[String] = None
    Engine: String
    EngineVersion: Optional[String] = None
    Filters: Optional[FilterList] = None
    LicenseModel: Optional[String] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None
    Vpc: Optional[BooleanOptional] = None


class DescribePendingMaintenanceActionsMessage(BaseModel):
    Filters: Optional[FilterList] = None
    Marker: Optional[String] = None
    MaxRecords: Optional[IntegerOptional] = None
    ResourceIdentifier: Optional[String] = None


class FailoverDBClusterResult(BaseModel):
    DBCluster_1: Optional[DBCluster] = Field(None, alias='DBCluster')


class GlobalCluster(BaseModel):
    DeletionProtection: Optional[BooleanOptional] = None
    Engine: Optional[String] = None
    EngineVersion: Optional[String] = None
    GlobalClusterArn: Optional[String] = None
    GlobalClusterIdentifier_1: Optional[GlobalClusterIdentifier] = Field(
        None, alias='GlobalClusterIdentifier'
    )
    GlobalClusterMembers: Optional[GlobalClusterMemberList] = None
    GlobalClusterResourceId: Optional[String] = None
    Status: Optional[String] = None
    StorageEncrypted: Optional[BooleanOptional] = None


class GlobalClusterList(RootModel[List[GlobalCluster]]):
    root: List[GlobalCluster]


class GlobalClustersMessage(BaseModel):
    GlobalClusters: Optional[GlobalClusterList] = None
    Marker: Optional[String] = None


class ModifyDBClusterResult(BaseModel):
    DBCluster_1: Optional[DBCluster] = Field(None, alias='DBCluster')


class ModifyDBInstanceResult(BaseModel):
    DBInstance_1: Optional[DBInstance] = Field(None, alias='DBInstance')


class ModifyGlobalClusterResult(BaseModel):
    GlobalCluster_1: Optional[GlobalCluster] = Field(None, alias='GlobalCluster')


class PromoteReadReplicaDBClusterResult(BaseModel):
    DBCluster_1: Optional[DBCluster] = Field(None, alias='DBCluster')


class RebootDBInstanceResult(BaseModel):
    DBInstance_1: Optional[DBInstance] = Field(None, alias='DBInstance')


class RemoveFromGlobalClusterResult(BaseModel):
    GlobalCluster_1: Optional[GlobalCluster] = Field(None, alias='GlobalCluster')


class RestoreDBClusterFromSnapshotResult(BaseModel):
    DBCluster_1: Optional[DBCluster] = Field(None, alias='DBCluster')


class RestoreDBClusterToPointInTimeResult(BaseModel):
    DBCluster_1: Optional[DBCluster] = Field(None, alias='DBCluster')


class StartDBClusterResult(BaseModel):
    DBCluster_1: Optional[DBCluster] = Field(None, alias='DBCluster')


class StopDBClusterResult(BaseModel):
    DBCluster_1: Optional[DBCluster] = Field(None, alias='DBCluster')


class CreateDBClusterResult(BaseModel):
    DBCluster_1: Optional[DBCluster] = Field(None, alias='DBCluster')


class CreateDBInstanceResult(BaseModel):
    DBInstance_1: Optional[DBInstance] = Field(None, alias='DBInstance')


class CreateGlobalClusterResult(BaseModel):
    GlobalCluster_1: Optional[GlobalCluster] = Field(None, alias='GlobalCluster')


class DeleteGlobalClusterResult(BaseModel):
    GlobalCluster_1: Optional[GlobalCluster] = Field(None, alias='GlobalCluster')


class FailoverGlobalClusterResult(BaseModel):
    GlobalCluster_1: Optional[GlobalCluster] = Field(None, alias='GlobalCluster')
